- 
  name: delete cluster 
  hosts: [kuber]
  tasks:
    - name: remove cluster
      become: true
      shell: | 
         kubeadm reset cleanup-node --force

    - name: remove /etc/kubernetes
      become: true
      file: 
        path: /etc/kubernetes
        state: absent

    - name: remove 
      file:
        path: "{{ ansible_env.HOME  }}/.kube"
        state: absent
